### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by boblauer** [TeehanLax/Hyperlapse.js#24]
If so, is the api documentation available anywhere online?

**Comment by gusfraser** [comment]
Not sure of much documentation but I managed to fork it and adapt for this: 

https://github.com/gusfraser/Hyperlapse-GPX
http://gpxhyperlapse.com 

Code kind of made sense to me. Check the examples. 

Any questions let me know, might be able to answer them but didn't write it originally.

**Comment by concretesniper** [comment]
how do you create a gpx file?

**Comment by mmehrle** [comment]
You go here:

http://www.gpsvisualizer.com/convert_input

Easiest is to drag and drop a Google maps link and then download the file. I tried it with the beta demo URL and it works. However the intervals and number of frames are too limited to make any sense.

**Comment by gusfraser** [comment]
Or, you use any kind of activity tracker that can output GPX files (Garmin sports watches, for example)

**Comment by liperuf** [comment]
thanks for posting your version @gusfraser 

I was struggling about convert a google maps route into gpx file at [gpsvisualizer](http://www.gpsvisualizer.com/convert_input). The screen below helped me a lot!

![Convert and export Google Maps route into GPX File (online way)](http://i.imgur.com/MDhvV0v.png?1)

source: [How to plan a route in Google Maps and export it to Gpx / your phone](http://bedsforcyclists.co.uk/articles/2014/04/13/how-to-plan-a-route-in-google-maps-and-export-it-to-gpx-your-phone/)

**Comment by davidchrest** [comment]
What happened to http://hyperlapse.tllabs.io/? Is there any sample code that works?

**Comment by afang** [comment]
I'm maintaining [a fork of Hyperlapse](https://github.com/afang/hyperlapse.js). It seems like the current version is no longer working with the new Maps API.

**Comment by davidchrest** [comment]
Yes, I found that fork soon after in another discussion thread. Thanks so much!
