### ISSUE TITLE
examples showing how to change resolution and amount of frames per animation

### ISSUE THREAD

**Issue by amigax** [TeehanLax/Hyperlapse.js#3]
hey there you got any examples showing how to change resolution and amount of frames per animation? Cant seem to find where to tweak the script.

**Comment by pnitsch** [comment]
Check out the source of http://tllabs.io/hyperlapse/examples/simple.html

You can add options to the parameters object in the constructor (as per http://tllabs.io/hyperlapse/docs/Hyperlapse.html).

For example, to have a maximum of 200 points with the highest resolution, do this -

``` js
var hyperlapse = new Hyperlapse(document.getElementById('pano'), {
    lookat: new google.maps.LatLng(37.81409525128964,-122.4775045005249),
    zoom: 3,
    max_points: 200,
    elevation: 50
});
```

Keep in mind, zoom level 3 is very memory intensive. You'll need a really good machine for it.

**Comment by amigax** [comment]
thats excellent! Thanks, im having lots of fun with this script, Im trying now to save the images and not display them, so I can simply get the files to assemble in after effects, do you guys have any way to do this ? I tried hacking in Canvas2Image.saveAsPNG(canvas); after context.drawImage(this.canvas, 0, 0); and it works for one image then stops. Im not great at JS unfortunately so any help would be good, im sure if it didnt store them in the memory and just wrote them out then we could grab literally millions of images with no memory restriction. Thanks again.

**Comment by fridde** [comment]
@amiga: did you have any progress yet? 
I'm not a js-programmer either, but I'd like to make longer videos of several minutes. my first approach was to use the manual on http://www.oampo.co.uk/2011/01/exporting-video-from-webgl/ , with no success. 

Then I added FileSaver.js into the header of the viewer and, within Hyperlapse.js, changed the function _loader.onPanoramaLoad into

```
_h_points[_point_index].image = canvas;
canvas.toBlob(function(blob) {
saveAs(blob, _point.index + "image.png"); });
```

The viewer doesn't work anymore after this. Do you see any logical error?

**Comment by lahabana** [comment]
I do not know about your error. What I have done to export the video is to use phantomJS. to grab a screenshot of each image. My phantomjs does something like this:

``` js
var page = new WebPage();

page.onCallback = function(data) {
  if (data === "finished") {
    console.log("All images created, creating the video...");
    createVideo();
    return;
  }
  if (data === "loaded") {
    console.log("Starting to create images...");
    return;
  }
  console.log("Creating image number: " + data + "...");
  if (data !== 0) { // The first image is black so we don't render it
    page.render(imageDir + (data < 10 ? '0' + data : data)+ '.jpeg');
  }
}

page.open('./simple.html', function(status) {
  if (status !== 'success') {
    console.log('Unable to access network');
  } else {
    console.log('Page loaded, loading Hyperlapse data...');
  }
}); 
```

And then in the js I animate manually and call the callback:

``` js
window.onload = function init() {
      // Describe each Hyperlapse part
      var data = [{"origin":"43.454346,-3.936979","destination":"43.43079,-3.94539","elevation":0,"fov":80,"distance_between_points":1,"max_points":800}];
      // General parameters
      HyperlapseJob.max_points = 100;
      HyperlapseJob.distance_between_points = 5;

      window.callPhantom = window.callPhantom || function(data) {
        console.log(data);
      };

      // We create the queue with our data
      var HQ = new HyperlapseQueue(document.getElementById('pano'),
                                   {data: data, max_points: 100, distance_between_points: 5});
      // the callback when all Hyperlapses have been played
      HQ.onFinish = function() {
        console.log('finished');
        window.callPhantom("finished");
      };

      // Each time a new image is displayed
      HQ.onFrame = function(idx) {
        window.callPhantom(idx);
      };

      // Each time a new Hyperlapse is fully loaded
      HQ.onLoadComplete = function() {
        window.callPhantom("loaded");
      };

      // Start the Hyperlapse queue
      HQ.startNext();
    };
```

HyperlapseQueue is just a wrapper around multiple Hyperlapses. If you want I can share you my code

**Comment by fridde** [comment]
Thanks! Definitely great help!
Yes, I would appreciate the wrapper!

**Comment by lahabana** [comment]
Here it is: https://gist.github.com/lahabana/5a07d36ad366b63e6469 this goes further as it enables you to have more than one hyperlapse sequence and play them one after the other.

**Comment by mootmoot75** [comment]
@lahabana Hi, i'm brand new to the Java scene, i spent some days figuring out phantomjs and this great tool that is Hyperlapse. i use the code you provided with phantomjs to grab screenshots in order to quickly export hyperlapses...

everything works fine except the "look_at", i cannot figure how to make it work with your code. i've been trying all day, maybe you have a tip for me ?
