### ISSUE TITLE
Null lookat throws exception

### ISSUE THREAD

**Issue by markhowellsmead** [TeehanLax/Hyperlapse.js#4]
Terrific work. I've installed the Git repo locally and it's working excellently, for everything except a sequence with param lookat set to null (or not passed in), or use_lookat set to false. In both instances, the play method throws "Uncaught TypeError: Cannot read property 'jb' of null" to the console. Is the following config correct?

<pre>var hyperlapse = new Hyperlapse(document.getElementById('pano'),{use_lookat: false, zoom: 2, elevation: 50 });</pre>

**Comment by pnitsch** [comment]
I'll look into this. That shouldn't happen.

**Comment by pnitsch** [comment]
I had to change the default to false. It was a bug in the drawMaterial method. You don't actually have to include it in the constructor parameters if you do not want a look-at point.

This changes things for folks that don't have it specified and want a look-at. Be careful. 

``` js
var hyperlapse = new Hyperlapse(document.getElementById('pano'), {
    zoom: 2,
    use_lookat: true,
    elevation: 50
});
```

**Comment by markhowellsmead** [comment]
Confirmed; many thanks for such a prompt response!
